name: William Dodson
url: http://williamdodson.co
markdown: kramdown
highlighter: rouge
destination: public
encoding: UTF-8
timezone: 'America/New_York'
permalink: /:categories/:title/
exclude: [sass, node_modules, rsync.sh, README.md]
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# XML feed settings
description: 'Creative Design & Development Services Made with Love'
feed:
  path: feed.articles.atom

# gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
