name: William Dodson
url: http://williamdodson.co
markdown: kramdown
# pygments: true
highlighter: rouge
destination: public
# relative_permalinks: true
encoding: UTF-8
timezone: '-0400'
#paginate: 12
#paginate_path: "/articles/page:num/"
permalink: /:categories/:title/
exclude: [sass, config.rb, rsync.sh, README.md, williamdodson.sublime-project, williamdodson.sublime-workspace]
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# XML feed settings
description: 'Creative Design & Development Services Made with Love'
feed:
  path: feed.articles.atom

# gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
