name: William Dodson
url: http://williamdodson.co
markdown: redcarpet
pygments: true
destination: public
relative_permalinks: true
encoding: UTF-8
permalink: /:categories/:title
exclude: [sass, config.rb]
tag_page_layout: tag_page
tag_page_dir: tag

# XML feed settings
description: 'Creative Design & Development Services Made with Love'